# https://docs.docker.com/build/ci/github-actions/examples/
name: CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  release:
    types:
      - published

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm lint

      - name: Format Check
        run: pnpm format:check

      - name: Package
        run: pnpm package

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: extension-archive
          path: copy-as-markdown-quote.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: extension-dist
          path: dist
